services:
  web:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - alpha-net

  celery_worker:
    build: ./backend
    command: celery -A celery_worker.celery_app worker --loglevel=info
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - alpha-net

  db:
    image: postgres:17.5-bullseye
    environment:
      POSTGRES_DB: alphadb
      POSTGRES_USER: alphauser
      POSTGRES_PASSWORD: alphapass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - alpha-net

  redis:
    image: redis:8.0.3-alpine
    networks:
      - alpha-net

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - web
  #   networks:
  #     - alpha-net

volumes:
  pgdata:

networks:
  alpha-net:
    driver: bridge
