"""Initial tables

Revision ID: 33baad513e78
Revises: 
Create Date: 2025-07-27 11:14:52.113065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33baad513e78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('people_company_id_fkey'), 'people', type_='foreignkey')
    op.create_foreign_key(None, 'people', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_foreign_key(op.f('people_company_id_fkey'), 'people', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
