"""Add company_id and person_id to snippet/log

Revision ID: f1bc795b91f4
Revises: 33baad513e78
Create Date: 2025-07-27 17:18:47.421456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bc795b91f4'
down_revision: Union[str, Sequence[str], None] = '33baad513e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_snippets', sa.Column('person_id', sa.UUID(), nullable=True))
    op.add_column('context_snippets', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'context_snippets', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'context_snippets', 'people', ['person_id'], ['id'], ondelete='SET NULL')
    op.add_column('search_logs', sa.Column('person_id', sa.UUID(), nullable=True))
    op.add_column('search_logs', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'search_logs', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'search_logs', 'people', ['person_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_logs', type_='foreignkey')
    op.drop_constraint(None, 'search_logs', type_='foreignkey')
    op.drop_column('search_logs', 'company_id')
    op.drop_column('search_logs', 'person_id')
    op.drop_constraint(None, 'context_snippets', type_='foreignkey')
    op.drop_constraint(None, 'context_snippets', type_='foreignkey')
    op.drop_column('context_snippets', 'company_id')
    op.drop_column('context_snippets', 'person_id')
    # ### end Alembic commands ###
